### ISSUE TITLE
crashes when something is unexpected

### ISSUE THREAD

**Issue by miopa** [FarmRadioHangar/fconf#7]
I suppose it's trying to find the interface name from file with old json structure

`fconf w --disable`
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x189cc]

goroutine 1 [running]:
panic(0x1ab488, 0x10526008)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x33c
github.com/urfave/cli.HandleAction.func1(0x105336f8)
        /Volumes/gernest/personal/gopath/src/github.com/urfave/cli/app.go:478 +0x290
panic(0x1ab488, 0x10526008)
        /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x454
main.DisableWifi(0x1058c140, 0x0, 0x0)
        /Volumes/gernest/personal/gopath/src/github.com/FarmRadioHangar/fconf/wifi.go:164 +0x4c
main.WifiClientCMD(0x1058c140, 0x0, 0x0)
        /Volumes/gernest/personal/gopath/src/github.com/FarmRadioHangar/fconf/wifi.go:25 +0x94
reflect.Value.call(0x1a20f0, 0x1e3094, 0x13, 0x1c721a, 0x4, 0x105336b8, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:434 +0xd68
reflect.Value.Call(0x1a20f0, 0x1e3094, 0x13, 0x105336b8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:302 +0x84
github.com/urfave/cli.HandleAction(0x1a20f0, 0x1e3094, 0x1058c140, 0x0, 0x0)
        /Volumes/gernest/personal/gopath/src/github.com/urfave/cli/app.go:487 +0x1d0
github.com/urfave/cli.Command.Run(0x1c8b60, 0xb, 0x0, 0x0, 0x10526250, 0x1, 0x1, 0x1ce794, 0x23, 0x0, ...)
        /Volumes/gernest/personal/gopath/src/github.com/urfave/cli/command.go:191 +0xc10
github.com/urfave/cli.(*App).Run(0x1057c0c0, 0x1050a300, 0x3, 0x4, 0x0, 0x0)
        /Volumes/gernest/personal/gopath/src/github.com/urfave/cli/app.go:240 +0x798
main.main()
        /Volumes/gernest/personal/gopath/src/github.com/FarmRadioHangar/fconf/main.go:164 +0x13d8
```

**Comment by gernest** [comment]
@miopa is the state file in the new format?

**Comment by gernest** [comment]
@miopa I need more info, like the version of fconf and the contents of state file!

**Comment by miopa** [comment]
fconf 0.4.2, the state file was in the wrong format
